version: '3'
services:
  web:
    build:
      context: .
    volumes:
      - .:/todo_plug
    ports:
      - "3000:3000"
    links:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "todo_plug"    
